
export const ERROR_CODES = {
  CONFLICT_EMAIL: 'CONFLICT_EMAIL',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  ACCOUNT_TYPE_ALREADY_EXISTS:'ACCOUNT_TYPE_ALREADY_EXISTS',
  SUB_ACCOUNT_TYPE_ALREADY_EXISTS:'SUB_ACCOUNT_TYPE_ALREADY_EXISTS',
  ACCOUNT_TYPE_HAS_CHILD:'ACCOUNT_TYPE_HAS_CHILD',
  OPENING_BALANCE_NOT_SET: 'OPENING_BALANCE_NOT_SET',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  MOVIE_NOT_FOUND:'MOVIE_NOT_FOUND',
  // add more as needed
} as const;

export type ERROR_CODES = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
